<a href="https://colab.research.google.com/github/laya7171/pytorch/blob/main/NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch
import torch.nn as nn
from torch.nn import Sequential

In [38]:
class model(nn.Module): #inherit from the nn.Moduel class (ie. base class which allows to use all layer and functions)

  def __init__(self, num_features):
    super().__init__() ##we call the parent class constructor to make sure all the behind the scence works is carried out *(must use)

    self.Linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):

    out = self.Linear(features)
    out = self.sigmoid(out)
    return out


In [39]:
#creating fake datasest

features = torch.rand(10,5)
features

tensor([[0.6506, 0.8171, 0.6007, 0.2049, 0.6461],
        [0.3024, 0.1713, 0.4880, 0.6442, 0.5989],
        [0.4664, 0.1003, 0.4601, 0.8061, 0.0223],
        [0.6584, 0.4478, 0.6170, 0.3761, 0.3784],
        [0.2500, 0.1180, 0.5394, 0.0226, 0.9469],
        [0.1119, 0.8502, 0.6641, 0.4856, 0.4535],
        [0.6481, 0.2976, 0.8704, 0.8403, 0.1363],
        [0.3601, 0.4870, 0.8720, 0.6014, 0.8067],
        [0.5783, 0.4026, 0.5546, 0.4387, 0.6263],
        [0.4428, 0.4579, 0.0408, 0.4414, 0.5454]])

In [40]:
model = model(features.shape[1])

In [41]:
model(features) # this is the standard way to call the forward function

tensor([[0.4110],
        [0.3280],
        [0.3123],
        [0.3676],
        [0.3775],
        [0.3921],
        [0.3098],
        [0.3422],
        [0.3589],
        [0.3796]], grad_fn=<SigmoidBackward0>)

In [42]:
model.Linear.weight

Parameter containing:
tensor([[-0.0456,  0.3274, -0.1223, -0.4036, -0.0359]], requires_grad=True)

In [43]:
model.Linear.bias

Parameter containing:
tensor([-0.4184], requires_grad=True)

In [44]:
!pip install torchinfo

In [45]:
from torchinfo import summary

summary(model, input_size = [10,5] )

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [46]:
class Model2(nn.Module):

  def __init__(self, input_features):
    super().__init__()

    self.network = nn.Sequential(
         nn.Linear(input_features,3),
         nn.ReLU(),
         nn.Linear(3, 1),
         nn.Sigmoid()
    )


  def forward(self, input):
    y_pred = self.network(dataset)

    return y_pred


In [47]:
dataset = torch.rand(5,5)

In [48]:
model2 = Model2(dataset.shape[1])

In [49]:
model2(dataset)

tensor([[0.6071],
        [0.6521],
        [0.6089],
        [0.5955],
        [0.6075]], grad_fn=<SigmoidBackward0>)

In [50]:
summary ( model2, input_size= dataset.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [5, 1]                    --
├─Sequential: 1-1                        [5, 1]                    --
│    └─Linear: 2-1                       [5, 3]                    18
│    └─ReLU: 2-2                         [5, 3]                    --
│    └─Linear: 2-3                       [5, 1]                    4
│    └─Sigmoid: 2-4                      [5, 1]                    --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00