<a href="https://colab.research.google.com/github/laya7171/pytorch/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader

In [78]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [79]:
df.shape

(569, 33)

In [80]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [81]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [82]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [83]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [84]:
X_train

array([[ 0.0253617 ,  0.54562637,  0.06173111, ...,  0.4833354 ,
         1.1933024 ,  0.96645132],
       [ 3.1744228 ,  1.29391323,  3.31356831, ...,  2.71347605,
        -0.90387164,  1.17141586],
       [ 0.45595346, -0.04080534,  0.62423589, ...,  1.56385425,
         2.30297216,  1.16587628],
       ...,
       [ 1.24250108, -0.4395789 ,  1.21722533, ...,  0.82256807,
        -0.64087652,  0.58145036],
       [ 1.70179897,  1.04761191,  1.77680693, ...,  1.23090368,
         0.6893698 ,  0.59474536],
       [-0.75831531, -0.1510545 , -0.78557564, ..., -0.7972679 ,
         0.70973071, -0.75303496]])

In [85]:
y_train

36     M
82     M
351    M
425    B
493    B
      ..
222    B
473    B
498    M
302    M
55     B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [86]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [87]:
y_train

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

### Numpy arrays to PyTorch tensors

In [88]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [89]:
X_train_tensor.shape

torch.Size([455, 30])

In [90]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [91]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





In [92]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [93]:
tranning_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [94]:
learning_rate = 0.1
epochs = 25
batch_size = 32

In [95]:
train_loader = DataLoader(tranning_dataset, batch_size = batch_size, shuffle = True)
test_loader = DataLoader(tranning_dataset, batch_size = batch_size, shuffle = True)

### Important Parameters

### Training Pipeline

In [96]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  for batch_features , batch_label in train_loader:
  # forward pass
    y_pred = model.forward(batch_features)

  # loss calculate
    loss = model.loss_function(y_pred, batch_label.view(-1,1))

  # backward pass
    loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 2.927610193761652
Epoch: 2, Loss: 1.7594891879566532
Epoch: 3, Loss: 1.344237780869563
Epoch: 4, Loss: 1.3037269960505213
Epoch: 5, Loss: 1.5857600092092816
Epoch: 6, Loss: 1.2274794484380742
Epoch: 7, Loss: 1.783722798529301
Epoch: 8, Loss: 1.0609649422778118
Epoch: 9, Loss: 2.40054011043449
Epoch: 10, Loss: 1.1879367882905618
Epoch: 11, Loss: 1.3203516942659559
Epoch: 12, Loss: 1.1984437806217325
Epoch: 13, Loss: 1.5551763532292484
Epoch: 14, Loss: 1.8512645171843718
Epoch: 15, Loss: 1.422489375328109
Epoch: 16, Loss: 1.0136757265067287
Epoch: 17, Loss: 1.5463305654432309
Epoch: 18, Loss: 1.6632764319996844
Epoch: 19, Loss: 1.6714157485860506
Epoch: 20, Loss: 0.975907416087143
Epoch: 21, Loss: 0.8785783949939097
Epoch: 22, Loss: 1.2157823907120084
Epoch: 23, Loss: 2.188645846851817
Epoch: 24, Loss: 1.9055050313330923
Epoch: 25, Loss: 1.7463323648021798


In [97]:
model.bias

tensor([-1.5054], dtype=torch.float64, requires_grad=True)

### Evaluation

In [98]:
# model evaluation
with torch.no_grad():
  for batch_feature , batch_label in test_loader:
    y_pred = model.forward(batch_feature)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == batch_label).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.7142857313156128
