<a href="https://colab.research.google.com/github/laya7171/pytorch/blob/main/pytorch_tranning_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [219]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler #to scale the value range
from sklearn.preprocessing import LabelEncoder #to convert the categorical value to numerical

In [220]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [221]:
df.shape

(569, 33)

In [222]:
df.drop(columns=["id","Unnamed: 32"], inplace = True)

In [223]:
#train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [224]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [225]:
X_test

array([[ 2.98143536,  0.28822297,  3.1660216 , ...,  1.71859906,
         0.52218473, -0.22520538],
       [ 1.44167813,  0.55516167,  1.37436974, ...,  1.01412384,
        -0.54882087, -0.99675195],
       [-0.2836619 , -1.14747435, -0.28774485, ..., -0.83378068,
        -0.73876075,  0.90549069],
       ...,
       [ 0.88203002,  0.30265209,  0.78976972, ..., -0.04949562,
         0.60677981, -1.06195307],
       [ 2.70306117,  1.84416295,  2.85900144, ...,  2.4629792 ,
         0.48387752,  0.18393164],
       [-0.14737453,  2.21451033, -0.21162068, ..., -0.84437083,
        -0.32057377, -0.74029422]])

In [226]:
y_train

11     M
436    B
178    B
395    B
350    B
      ..
348    B
183    B
342    B
424    B
52     B
Name: diagnosis, Length: 455, dtype: object

In [227]:
encoder = LabelEncoder()

In [228]:
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [229]:
y_test

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0])

In [230]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,

In [231]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

#now all the np.array are converted into the tensor

In [232]:
X_train_tensor.shape

torch.Size([455, 30])

In [233]:
y_train_tensor.shape

torch.Size([455])

# Creating a model

In [234]:
class myNN:
  def __init__(self, X):

    self.weight = torch.rand(X.shape[1], 1 , dtype = torch.float64, requires_grad= True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

  def forward_pass(self, X):
    z = torch.matmul(X, self.weight) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss



In [235]:
learning_rate = 0.01
epochs = 25

In [236]:
#creating a model

model = myNN(X_train_tensor)
model.weight

tensor([[2.0404e-01],
        [5.4664e-02],
        [8.9325e-01],
        [4.0645e-01],
        [2.0983e-02],
        [7.8657e-01],
        [2.4851e-01],
        [8.2496e-01],
        [9.4540e-01],
        [3.5086e-01],
        [8.3359e-01],
        [2.1017e-01],
        [6.0175e-02],
        [7.2173e-04],
        [4.5903e-01],
        [8.6817e-01],
        [9.2965e-01],
        [3.7539e-01],
        [9.5004e-01],
        [8.5222e-01],
        [4.5374e-01],
        [9.3163e-01],
        [4.2115e-01],
        [3.5785e-01],
        [6.8003e-01],
        [5.1499e-01],
        [3.3413e-01],
        [9.5443e-01],
        [5.2901e-01],
        [3.4913e-02]], dtype=torch.float64, requires_grad=True)

In [237]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [238]:
#create model
#define loop
#forwardpass
#calculate loss
#backward pass
#update the weights

In [239]:
for epoch in range(epochs):
  y_pred = model.forward_pass(X_train_tensor)

  loss = model.loss_function(y_pred , y_train_tensor)

  loss.backward()
  with torch.no_grad():
    model.weight -= learning_rate * model.weight.grad
    model.bias -= learning_rate * model.bias.grad

  model.weight.grad.zero_()
  model.bias.grad.zero_()  #in new epoch we need to find the new gradient

  print(f"Epochs {epoch +1}, loss: {loss}")


Epochs 1, loss: 3.7196470370521344
Epochs 2, loss: 3.707811183482631
Epochs 3, loss: 3.6959108201963358
Epochs 4, loss: 3.683737573410905
Epochs 5, loss: 3.6715295123722913
Epochs 6, loss: 3.659201909926651
Epochs 7, loss: 3.64688573396577
Epochs 8, loss: 3.634581107256231
Epochs 9, loss: 3.62228815256168
Epochs 10, loss: 3.6100069926000677
Epochs 11, loss: 3.597737750011736
Epochs 12, loss: 3.585480547348636
Epochs 13, loss: 3.5731520794218756
Epochs 14, loss: 3.560483691139114
Epochs 15, loss: 3.547828229563503
Epochs 16, loss: 3.535068753624472
Epochs 17, loss: 3.5222033012961407
Epochs 18, loss: 3.5093514611593024
Epochs 19, loss: 3.4964902493609364
Epochs 20, loss: 3.4835579883169436
Epochs 21, loss: 3.4706396211556734
Epochs 22, loss: 3.4576469186157714
Epochs 23, loss: 3.444456634015648
Epochs 24, loss: 3.4311446892061985
Epochs 25, loss: 3.4178477168191628


# Evaluation

In [247]:
with torch.no_grad():
  y_pred = model.forward_pass(X_test_tensor)
  y_pred = (y_pred > 0.5).float() # will return true for value greater than 0.5 and then .float() will give the 1 or 0
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(accuracy) # compares one to one and then will give true or false then convert to mean then average it

tensor(0.5083)
