<a href="https://colab.research.google.com/github/laya7171/pytorch/blob/main/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
print(torch.__version__)

2.8.0+cu126


In [4]:
if torch.cuda.is_available():
  print("The model works in gpu")
  print(f"The GPU version is {torch.cuda.get_device_name(0)}")
else:
  print("The model is working in cpu")


The model works in gpu
The GPU version is Tesla T4


## Creating tensors

In [5]:
#using empty
a = torch.empty(2,3) #allocates space in memory and shows the existing value in the memory
print(a)

tensor([[3.7956e-16, 4.4159e-41, 3.7956e-16],
        [4.4159e-41, 0.0000e+00, 0.0000e+00]])


In [6]:
#check type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,2) #similar to using the numpy zeros (can be used to initialize the bias in the NN)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
torch.ones(1,1)

tensor([[1.]])

In [9]:
torch.rand(3,3) #random number form 0-1 in the shape 3,3

tensor([[0.7591, 0.3063, 0.4518],
        [0.4731, 0.8637, 0.8199],
        [0.4947, 0.1717, 0.2459]])

In [10]:
torch.manual_seed(100)
torch.rand(3,3) #we use this to get deterministic answer from the rand function

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [11]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [12]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
torch.linspace(1,100,10)

tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [14]:
torch.eye(3,3) #the eye stands for identiy

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
torch.full((3,3),5) # 3x3 matrix of the all value 5

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
y = torch.empty_like(x)
print(y) #same shape like x but the values are different

tensor([[0, 0, 0],
        [0, 1, 0]])


In [19]:
y = torch.zeros_like(x)
y

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
y = torch.rand_like(x, dtype= float)
print(y)

tensor([[0.9443, 0.8848, 0.3006],
        [0.2113, 0.0521, 0.4188]], dtype=torch.float64)


# Tensor Datatypes

In [21]:
#find the data type
x.dtype

torch.int64

In [22]:
#assign datatype
x = torch.tensor([1.0,2.0,3.0], dtype= float)
x.dtype

torch.float64

In [23]:
x.to(float)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
x.dtype

torch.float64

# Mathematical operations (tensor and scalar)

In [25]:
x = torch.tensor([1,2,3])
y = 2

In [26]:
#addition
x = x+y
x

tensor([3, 4, 5])

In [27]:
#subtraction, multiplication and division are all same
x = x-y
x

tensor([1, 2, 3])

In [28]:
#mod
x = (x%100)/y
x

tensor([0.5000, 1.0000, 1.5000])

In [29]:
#power
x = x**y
x

tensor([0.2500, 1.0000, 2.2500])

# Element wise operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3
)
print(a)
print(b)

tensor([[0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445]])
tensor([[0.4892, 0.2426, 0.7003],
        [0.5277, 0.2472, 0.7909]])


In [31]:
#tensor addition
sum = a+b
sum

#subtraction
diff = a-b
diff

tensor([[ 0.3346,  0.3132,  0.2767],
        [-0.0837,  0.7007, -0.0464]])

In [32]:
c = torch.tensor([1,2,-3,-1])
print(c.abs())

tensor([1, 2, 3, 1])


In [33]:
print(c.neg())

tensor([-1, -2,  3,  1])


In [35]:
d = torch.tensor([1.3,3.2,3.9])
print(f"celling {torch.ceil(c)}")
print(f"floor {c.floor()}")

celling tensor([ 1,  2, -3, -1])
floor tensor([ 1,  2, -3, -1])


In [36]:
#clamp
torch.clamp(d, max =3, min= 2)

tensor([2., 3., 3.])

# Reduction operation|

In [39]:
e = torch.randint(size =(2,3), low = 1, high = 10)

In [40]:
e

tensor([[9, 3, 7],
        [7, 4, 9]])

In [42]:
#sum

torch.sum(e)

tensor(39)

In [46]:
torch.sum(e[0], dim = -1)

tensor(19)

In [49]:
torch.mean(e, dtype = torch.float32)

tensor(6.5000)

In [50]:
torch.median(e, dim = 1)

torch.return_types.median(
values=tensor([7, 7]),
indices=tensor([2, 0]))

In [51]:
torch.max(e)
torch.min(e)

tensor(3)

In [63]:
torch.argmax(e[1])

tensor(2)

In [62]:
torch.argmax(e)

tensor(0)

In [64]:
torch.argmin(e)

tensor(1)

# Matrix Operation

In [69]:
mat1 = torch.randint(size =(3,3), low= 1, high= 10)
mat2 = torch.randint(size =(3,3), low= 1, high= 10)

In [71]:
#matrix mulitplication
torch.matmul(mat1, mat2)

tensor([[50, 15, 26],
        [80, 33, 17],
        [74, 22, 31]])

In [73]:
mat1 = torch.tensor([1,2,3])
mat2 = torch.tensor([4,5,6])

torch.dot(mat1, mat2)

tensor(32)

In [79]:
#transpose
torch.transpose(mat1, 0, 0)

tensor([1, 2, 3])

# comparision operators

In [86]:
i = torch.randint(size = (3,3), low = 1, high = 10)
j = torch.randint(size = (3,3), low = 1, high = 10)

In [87]:
i>j

tensor([[False,  True, False],
        [False, False, False],
        [False,  True, False]])

In [88]:
i<j

tensor([[ True, False,  True],
        [ True,  True,  True],
        [False, False,  True]])

In [89]:
i=j

In [90]:
i!=j

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

# special functions

In [91]:
k = torch.randint(size = (3,3), low = 1 , high = 10)

In [92]:
torch.log(k)

tensor([[1.9459, 1.7918, 1.6094],
        [0.6931, 0.0000, 2.0794],
        [1.7918, 1.9459, 0.6931]])

In [93]:
torch.exp(k)

tensor([[1.0966e+03, 4.0343e+02, 1.4841e+02],
        [7.3891e+00, 2.7183e+00, 2.9810e+03],
        [4.0343e+02, 1.0966e+03, 7.3891e+00]])

In [95]:
torch.sqrt(k)

tensor([[2.6458, 2.4495, 2.2361],
        [1.4142, 1.0000, 2.8284],
        [2.4495, 2.6458, 1.4142]])

# Inplace operation(_ will replace thea actual value)

In [100]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [103]:
m = m.add_(n)

In [104]:
m.relu_()

tensor([[1.3501, 1.0769, 0.1227],
        [1.4047, 0.8966, 1.3610]])

In [105]:
print(m)

tensor([[1.3501, 1.0769, 0.1227],
        [1.4047, 0.8966, 1.3610]])


# Copy tensor

In [110]:
a = torch.rand(3,3)
a

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634],
        [0.8993, 0.2732, 0.3397]])

In [111]:
b = a

In [112]:
b

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634],
        [0.8993, 0.2732, 0.3397]])

In [113]:
a[0][0] = 10

In [114]:
a

tensor([[10.0000,  0.2651,  0.2336],
        [ 0.5057,  0.5688,  0.0634],
        [ 0.8993,  0.2732,  0.3397]])

In [115]:
b

tensor([[10.0000,  0.2651,  0.2336],
        [ 0.5057,  0.5688,  0.0634],
        [ 0.8993,  0.2732,  0.3397]])

In [116]:
print(id(b))
print(id(a))

135342710736368
135342710736368


In [117]:
#the new b will only point to the original location of a variable so we use clone to create a new tensor

In [118]:
b = a.clone()

In [119]:
b

tensor([[10.0000,  0.2651,  0.2336],
        [ 0.5057,  0.5688,  0.0634],
        [ 0.8993,  0.2732,  0.3397]])

In [120]:
print(id(a))
print(id(b))

135342710736368
135342710468160


# Tensor Operation in GPU

In [121]:
torch.cuda.is_available()

True

In [122]:
device = torch.device('cuda')

In [123]:
#create new tensor in GPU
torch.rand(2,3, device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [125]:
#move an existing tensor to gpu
a = torch.rand(3,3)
a

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521],
        [0.5569, 0.9952, 0.0015]])

In [127]:
b = a.to(device)

In [128]:
b = b + 5

In [129]:
b

tensor([[5.9815, 5.1132, 5.4783],
        [5.4436, 5.3847, 5.4521],
        [5.5569, 5.9952, 5.0015]], device='cuda:0')

# Reshaping tensor

In [130]:
a = torch.rand(4,4)

In [131]:
a.reshape(2,2,2,2)

tensor([[[[0.0813, 0.4907],
          [0.2130, 0.4603]],

         [[0.1386, 0.0277],
          [0.5662, 0.3503]]],


        [[[0.6555, 0.7667],
          [0.2269, 0.7555]],

         [[0.6458, 0.3673],
          [0.1770, 0.2966]]]])

In [132]:
 #flatten
 a.flatten()

tensor([0.0813, 0.4907, 0.2130, 0.4603, 0.1386, 0.0277, 0.5662, 0.3503, 0.6555,
        0.7667, 0.2269, 0.7555, 0.6458, 0.3673, 0.1770, 0.2966])

In [133]:
#permute

b = torch.rand(2,3,4)

In [134]:
b

tensor([[[0.9925, 0.2103, 0.1292, 0.1719],
         [0.9127, 0.6818, 0.1953, 0.9991],
         [0.1133, 0.0135, 0.1450, 0.7819]],

        [[0.3134, 0.2983, 0.3436, 0.2028],
         [0.9792, 0.4947, 0.3617, 0.9687],
         [0.0359, 0.3041, 0.9867, 0.1290]]])

In [136]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [137]:
#unsqueeze
c = torch.rand(226, 226, 3)

In [139]:
c.unsqueeze(dim = 1)

tensor([[[[0.6887, 0.1637, 0.0899],
          [0.3139, 0.1219, 0.3516],
          [0.2316, 0.2847, 0.3520],
          ...,
          [0.2428, 0.4881, 0.6281],
          [0.8568, 0.9674, 0.4428],
          [0.0791, 0.6539, 0.3447]]],


        [[[0.7785, 0.6370, 0.2124],
          [0.9821, 0.4343, 0.2382],
          [0.6962, 0.4898, 0.0646],
          ...,
          [0.9809, 0.8731, 0.1416],
          [0.8880, 0.5099, 0.3832],
          [0.7232, 0.6196, 0.4628]]],


        [[[0.0739, 0.6235, 0.4039],
          [0.5057, 0.1776, 0.7293],
          [0.5721, 0.0961, 0.5017],
          ...,
          [0.9451, 0.9376, 0.9769],
          [0.1995, 0.9909, 0.0672],
          [0.4121, 0.3801, 0.9914]]],


        ...,


        [[[0.7815, 0.7430, 0.5677],
          [0.6829, 0.3753, 0.0321],
          [0.2815, 0.2480, 0.2798],
          ...,
          [0.2911, 0.4973, 0.3853],
          [0.9836, 0.5983, 0.8536],
          [0.4839, 0.5428, 0.4155]]],


        [[[0.3331, 0.7534, 0.5697],
         

In [140]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [141]:
import numpy as np

In [142]:
a = np.array([1,2,3])

In [143]:
a

array([1, 2, 3])

In [144]:
a.dtype

dtype('int64')

In [145]:
b = torch.tensor([5,6,7])

In [146]:
b = b.numpy

In [148]:
type(b)

builtin_function_or_method

In [150]:
torch.from_numpy(a)

tensor([1, 2, 3])